In [5]:
import numpy as np
arr1=np.arange(0,10)
arr2=np.ones((3,3))
arr3=np.zeros((2,5))
arr4=np.eye(4)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 练习2

In [47]:
arr5=np.random.randint(0,101,(5,5))
print(arr5)
print(arr5[2])
print(arr5[0:3,0:3])
n=[]
for i in arr5:
    for j in i:
        if j>50:
            n.append(j)
print(n)

[[ 22  66  71  96  42]
 [ 92  45  43  47   6]
 [ 79  46  73  17  23]
 [ 47 100  60  16   3]
 [ 32  26  97  39  80]]
[79 46 73 17 23]
[[22 66 71]
 [92 45 43]
 [79 46 73]]
[66, 71, 96, 92, 79, 73, 100, 60, 97, 80]


# 练习3

In [6]:
import numpy as np
arr6=np.random.randint(10,100,(6,6),dtype=np.int32)
print(arr6)
print(arr6[1])
print(arr6[:,3])
print(arr6[3:,3:])
m=arr6[0]
n=arr6[5]
print(m)
print(n)

[[20 59 68 59 70 75]
 [30 54 30 43 96 92]
 [69 92 66 84 61 74]
 [63 96 54 25 17 92]
 [92 32 57 37 32 51]
 [80 46 77 20 35 76]]
[30 54 30 43 96 92]
[59 43 84 25 37 20]
[[25 17 92]
 [37 32 51]
 [20 35 76]]
[20 59 68 59 70 75]
[80 46 77 20 35 76]


# 练习4

In [12]:
arr6[0]=n
print(arr6) #这个交换0行和5行我觉得我的逻辑没有问题，但不知道为什么运行结果不一样
arr6[5]=m
print(arr6)

[[80 46 77 20 35 76]
 [30 54 30 43 96 92]
 [69 92 66 84 61 74]
 [63 96 54 25 17 92]
 [92 32 57 37 32 51]
 [80 46 77 20 35 76]]
[[80 46 77 20 35 76]
 [30 54 30 43 96 92]
 [69 92 66 84 61 74]
 [63 96 54 25 17 92]
 [92 32 57 37 32 51]
 [80 46 77 20 35 76]]


In [68]:
arr7=np.zeros((8,8))
print(arr7)
a=[1,1,1,1,1,1,1,1]
b=[2,2,2,2,2,2,2,2]
arr7[0]=a
arr7[2]=a
arr7[4]=a
arr7[6]=a
arr7[1]=b
arr7[3]=b
arr7[5]=b
arr7[7]=b
print(arr7)
print(arr7[3][2:5])

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]]
[2. 2. 2.]


# 练习5

In [94]:
arr8=np.random.randint(0,51,(5,5),dtype=np.int32)
print(arr8)
t=[]
for i in arr8:
    for j in i:
        if j>25:
            t.append(j)
print(t)
print(np.where(arr8%2 == 0))
for i in range(5):
    for j in range(5):
        if arr8[i,j]<10:
            arr8[i,j]=-1
print(arr8)

[[48  2  3 43 35]
 [24 25 40 21 37]
 [41 25 18 44 35]
 [48 47 43 17  0]
 [40 21 13 48 38]]
[48, 43, 35, 40, 37, 41, 44, 35, 48, 47, 43, 40, 48, 38]
(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4]), array([0, 1, 0, 2, 2, 3, 0, 4, 0, 3, 4]))
[[48 -1 -1 43 35]
 [24 25 40 21 37]
 [41 25 18 44 35]
 [48 47 43 17 -1]
 [40 21 13 48 38]]


# 练习6

In [90]:
arr9=np.random.randint(0,51,(4,6),dtype=np.int32)
print(arr9)
np.mean(arr9)
a=arr9.T #求转置
print(np.max(a[0]))
print(np.max(a[1]))
print(np.max(a[2]))
print(np.max(a[3]))
print(np.max(a[4]))
print(np.max(a[5]))
print(np.min(arr9[0]))
print(np.min(arr9[1]))
print(np.min(arr9[2]))
print(np.min(arr9[3]))
print(np.std(arr9))

[[12  6 40 32 14 13]
 [15 43 40 46  2 10]
 [29  7 23 43 38 15]
 [34 20  1 46 49  7]]
34
43
40
46
49
15
6
2
7
1
15.630665639483603


In [ ]:
# 训练模型 
model_smote = DecisionTreeClassifier(criterion='entropy',random_state=42)
model_smote.fit(X_train_smote, y_train_smote)

# 在原始测试集上进行评估
y_pred = model_smote.predict(X_test)
print("混淆矩阵:")
print(confusion_matrix(y_test, y_pred))
print("\n分类报告:")
print(classification_report(y_test, y_pred, target_names=['0', '1']))
